apiVersion: 1

prune: true

datasources:
    - name: influxdb
      type: influxdb
      url: http://influxdb:8086
      orgId: 1
      uid: influxdb
      version: 1
      editable: false
      jsonData:
          version: Flux
          organization: nesquic
          defaultBucket: nesquic
          tlsSkipVerify: true
      secureJsonData:
          token: nesquic-token
