[package]
name = "noq-iut"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "nesquic-noq"
path = "src/main.rs"

[dependencies]
anyhow = "1.0.104"
bytes = "1.12.1"
tracing = "0.1.44"
noq = { version = "1.1.0", default-features = false, features = ["runtime-tokio", "rustls-aws-lc-rs", "bloom"] }
rustls = { version = "0.23.42", default-features = false, features = ["aws_lc_rs"] }
aws-lc-sys = { version = "0.45", features = ["bindgen"] }
socket2 = "0.6.5"
tokio = { version = "1.53.1", features = ["macros", "full"] }
utils = { path = "../../utils" }
iut-common = { path = "../common" }

[build-dependencies]
built = { version = "0.8", features = ["cargo-lock", "dependency-tree"] }
