{
 "title": "Quinn",
 "tags": "nesquic",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Throughput",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "targets": [
    { "expr": "throughput_sum{}", "query": "throughput_sum{}" }
   ]
  },
  { "title": "Unbounded", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "Server I/O Data Volume",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12.0, "x": 12.0, "y": 32 },
   "targets": [
    {
     "expr": "io_syscalls_data_volume_sum{mode='server', library='quinn', exported_job='test'}",
     "query": "io_syscalls_data_volume_sum{mode='server', library='quinn', exported_job='test'}"
    }
   ]
  },
  {
   "title": "Server I/O Syscalls",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12.0, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "io_syscalls_invocations_sum{mode='server', library='quinn', exported_job='test'}",
     "query": "io_syscalls_invocations_sum{mode='server', library='quinn', exported_job='test'}"
    }
   ]
  },
  {
   "title": "Client I/O Data Volume",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12.0, "x": 12.0, "y": 48 },
   "targets": [
    {
     "expr": "io_syscalls_data_volume_sum{mode='client', library='quinn', exported_job='test'}",
     "query": "io_syscalls_data_volume_sum{mode='client', library='quinn', exported_job='test'}"
    }
   ]
  },
  {
   "title": "Client I/O Syscalls",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12.0, "x": 0, "y": 40 },
   "targets": [
    {
     "expr": "io_syscalls_invocations_sum{mode='client', library='quinn', exported_job='test'}",
     "query": "io_syscalls_invocations_sum{mode='client', library='quinn', exported_job='test'}"
    }
   ]
  },
  { "title": "50ms Delay", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 56 } },
  {
   "title": "Server I/O Data Volume",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12.0, "x": 12.0, "y": 72 },
   "targets": [
    {
     "expr": "io_syscalls_data_volume_sum{mode='server', library='quinn', exported_job='delay50'}",
     "query": "io_syscalls_data_volume_sum{mode='server', library='quinn', exported_job='delay50'}"
    }
   ]
  },
  {
   "title": "Server I/O Syscalls",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12.0, "x": 0, "y": 64 },
   "targets": [
    {
     "expr": "io_syscalls_invocations_sum{mode='server', library='quinn', exported_job='delay50'}",
     "query": "io_syscalls_invocations_sum{mode='server', library='quinn', exported_job='delay50'}"
    }
   ]
  },
  {
   "title": "Client I/O Data Volume",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12.0, "x": 12.0, "y": 88 },
   "targets": [
    {
     "expr": "io_syscalls_data_volume_sum{mode='client', library='quinn', exported_job='delay50'}",
     "query": "io_syscalls_data_volume_sum{mode='client', library='quinn', exported_job='delay50'}"
    }
   ]
  },
  {
   "title": "Client I/O Syscalls",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12.0, "x": 0, "y": 80 },
   "targets": [
    {
     "expr": "io_syscalls_invocations_sum{mode='client', library='quinn', exported_job='delay50'}",
     "query": "io_syscalls_invocations_sum{mode='client', library='quinn', exported_job='delay50'}"
    }
   ]
  }
 ]
}