{
 "title": "XQUIC",
 "tags": "nesquic",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "nesquic_run",
    "label": "Run",
    "query": "import \"influxdata/influxdb/schema\"\nschema.tagValues(bucket: \"nesquic\", tag: \"nesquic_run\")"
   }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Throughput With Varying Connection Delay",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "query": "from(bucket: \"nesquic\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"nesquic\" and r._field == \"throughput\")\n  |> filter(fn: (r) => r.library == \"xquic\")\n  |> filter(fn: (r) => r.nesquic_run =~ /^${nesquic_run:regex}$/)\n  |> rename(columns: {\"_value\": \"throughput\"})\n  |> group()"
    }
   ]
  },
  { "title": "Unbounded", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "type": "text",
   "gridPos": { "h": 1.2, "w": 24, "x": 0, "y": 24 },
   "options": {
    "content": "This experiment runs the client and server in a separate network namespace, but does alter their traffic in any way."
   }
  },
  {
   "title": "Server I/O Syscalls",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12.0, "x": 0, "y": 32 },
   "targets": [
    {
     "query": "from(bucket: \"nesquic\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"nesquic_io\" and r._field == \"count\")\n  |> filter(fn: (r) => r.library == \"xquic\" and r.mode == \"server\" and r.job == \"unbounded\")\n  |> filter(fn: (r) => r.nesquic_run =~ /^${nesquic_run:regex}$/)\n  |> rename(columns: {\"_value\": \"count\"})\n  |> group()"
    }
   ]
  },
  {
   "title": "Server I/O Data Volume",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12.0, "x": 12.0, "y": 40 },
   "targets": [
    {
     "query": "from(bucket: \"nesquic\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"nesquic_io\" and r._field == \"volume_kb_sum\")\n  |> filter(fn: (r) => r.library == \"xquic\" and r.mode == \"server\" and r.job == \"unbounded\")\n  |> filter(fn: (r) => r.nesquic_run =~ /^${nesquic_run:regex}$/)\n  |> rename(columns: {\"_value\": \"volume_kb_sum\"})\n  |> group()"
    }
   ]
  },
  {
   "title": "Client I/O Syscalls",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12.0, "x": 0, "y": 48 },
   "targets": [
    {
     "query": "from(bucket: \"nesquic\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"nesquic_io\" and r._field == \"count\")\n  |> filter(fn: (r) => r.library == \"xquic\" and r.mode == \"client\" and r.job == \"unbounded\")\n  |> filter(fn: (r) => r.nesquic_run =~ /^${nesquic_run:regex}$/)\n  |> rename(columns: {\"_value\": \"count\"})\n  |> group()"
    }
   ]
  },
  {
   "title": "Client I/O Data Volume",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12.0, "x": 12.0, "y": 56 },
   "targets": [
    {
     "query": "from(bucket: \"nesquic\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"nesquic_io\" and r._field == \"volume_kb_sum\")\n  |> filter(fn: (r) => r.library == \"xquic\" and r.mode == \"client\" and r.job == \"unbounded\")\n  |> filter(fn: (r) => r.nesquic_run =~ /^${nesquic_run:regex}$/)\n  |> rename(columns: {\"_value\": \"volume_kb_sum\"})\n  |> group()"
    }
   ]
  },
  {
   "title": "ACK Frames Sent",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12.0, "x": 0, "y": 64 },
   "targets": [
    {
     "query": "from(bucket: \"nesquic\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"nesquic_quic\" and r._field == \"acks_sent\")\n  |> filter(fn: (r) => r.library == \"xquic\" and r.job == \"unbounded\")\n  |> filter(fn: (r) => r.nesquic_run =~ /^${nesquic_run:regex}$/)\n  |> rename(columns: {\"_value\": \"acks_sent\"})\n  |> group()"
    }
   ]
  },
  {
   "title": "Packets Sent",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12.0, "x": 12.0, "y": 64 },
   "targets": [
    {
     "query": "from(bucket: \"nesquic\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"nesquic_quic\" and r._field == \"packets_sent\")\n  |> filter(fn: (r) => r.library == \"xquic\" and r.job == \"unbounded\")\n  |> filter(fn: (r) => r.nesquic_run =~ /^${nesquic_run:regex}$/)\n  |> rename(columns: {\"_value\": \"packets_sent\"})\n  |> group()"
    }
   ]
  },
  { "title": "5ms Delay", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 72 } },
  {
   "type": "text",
   "gridPos": { "h": 1.2, "w": 24, "x": 0, "y": 80 },
   "options": {
    "content": "This experiment delays all traffic by 5ms."
   }
  },
  {
   "title": "Server I/O Syscalls",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12.0, "x": 0, "y": 88 },
   "targets": [
    {
     "query": "from(bucket: \"nesquic\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"nesquic_io\" and r._field == \"count\")\n  |> filter(fn: (r) => r.library == \"xquic\" and r.mode == \"server\" and r.job == \"delay5\")\n  |> filter(fn: (r) => r.nesquic_run =~ /^${nesquic_run:regex}$/)\n  |> rename(columns: {\"_value\": \"count\"})\n  |> group()"
    }
   ]
  },
  {
   "title": "Server I/O Data Volume",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12.0, "x": 12.0, "y": 96 },
   "targets": [
    {
     "query": "from(bucket: \"nesquic\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"nesquic_io\" and r._field == \"volume_kb_sum\")\n  |> filter(fn: (r) => r.library == \"xquic\" and r.mode == \"server\" and r.job == \"delay5\")\n  |> filter(fn: (r) => r.nesquic_run =~ /^${nesquic_run:regex}$/)\n  |> rename(columns: {\"_value\": \"volume_kb_sum\"})\n  |> group()"
    }
   ]
  },
  {
   "title": "Client I/O Syscalls",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12.0, "x": 0, "y": 104 },
   "targets": [
    {
     "query": "from(bucket: \"nesquic\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"nesquic_io\" and r._field == \"count\")\n  |> filter(fn: (r) => r.library == \"xquic\" and r.mode == \"client\" and r.job == \"delay5\")\n  |> filter(fn: (r) => r.nesquic_run =~ /^${nesquic_run:regex}$/)\n  |> rename(columns: {\"_value\": \"count\"})\n  |> group()"
    }
   ]
  },
  {
   "title": "Client I/O Data Volume",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12.0, "x": 12.0, "y": 112 },
   "targets": [
    {
     "query": "from(bucket: \"nesquic\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"nesquic_io\" and r._field == \"volume_kb_sum\")\n  |> filter(fn: (r) => r.library == \"xquic\" and r.mode == \"client\" and r.job == \"delay5\")\n  |> filter(fn: (r) => r.nesquic_run =~ /^${nesquic_run:regex}$/)\n  |> rename(columns: {\"_value\": \"volume_kb_sum\"})\n  |> group()"
    }
   ]
  },
  {
   "title": "ACK Frames Sent",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12.0, "x": 0, "y": 120 },
   "targets": [
    {
     "query": "from(bucket: \"nesquic\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"nesquic_quic\" and r._field == \"acks_sent\")\n  |> filter(fn: (r) => r.library == \"xquic\" and r.job == \"delay5\")\n  |> filter(fn: (r) => r.nesquic_run =~ /^${nesquic_run:regex}$/)\n  |> rename(columns: {\"_value\": \"acks_sent\"})\n  |> group()"
    }
   ]
  },
  {
   "title": "Packets Sent",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12.0, "x": 12.0, "y": 120 },
   "targets": [
    {
     "query": "from(bucket: \"nesquic\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"nesquic_quic\" and r._field == \"packets_sent\")\n  |> filter(fn: (r) => r.library == \"xquic\" and r.job == \"delay5\")\n  |> filter(fn: (r) => r.nesquic_run =~ /^${nesquic_run:regex}$/)\n  |> rename(columns: {\"_value\": \"packets_sent\"})\n  |> group()"
    }
   ]
  },
  { "title": "20ms Delay", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 128 } },
  {
   "type": "text",
   "gridPos": { "h": 1.2, "w": 24, "x": 0, "y": 136 },
   "options": {
    "content": "This experiment delays all traffic by 20ms."
   }
  },
  {
   "title": "Server I/O Syscalls",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12.0, "x": 0, "y": 144 },
   "targets": [
    {
     "query": "from(bucket: \"nesquic\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"nesquic_io\" and r._field == \"count\")\n  |> filter(fn: (r) => r.library == \"xquic\" and r.mode == \"server\" and r.job == \"delay20\")\n  |> filter(fn: (r) => r.nesquic_run =~ /^${nesquic_run:regex}$/)\n  |> rename(columns: {\"_value\": \"count\"})\n  |> group()"
    }
   ]
  },
  {
   "title": "Server I/O Data Volume",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12.0, "x": 12.0, "y": 152 },
   "targets": [
    {
     "query": "from(bucket: \"nesquic\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"nesquic_io\" and r._field == \"volume_kb_sum\")\n  |> filter(fn: (r) => r.library == \"xquic\" and r.mode == \"server\" and r.job == \"delay20\")\n  |> filter(fn: (r) => r.nesquic_run =~ /^${nesquic_run:regex}$/)\n  |> rename(columns: {\"_value\": \"volume_kb_sum\"})\n  |> group()"
    }
   ]
  },
  {
   "title": "Client I/O Syscalls",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12.0, "x": 0, "y": 160 },
   "targets": [
    {
     "query": "from(bucket: \"nesquic\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"nesquic_io\" and r._field == \"count\")\n  |> filter(fn: (r) => r.library == \"xquic\" and r.mode == \"client\" and r.job == \"delay20\")\n  |> filter(fn: (r) => r.nesquic_run =~ /^${nesquic_run:regex}$/)\n  |> rename(columns: {\"_value\": \"count\"})\n  |> group()"
    }
   ]
  },
  {
   "title": "Client I/O Data Volume",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12.0, "x": 12.0, "y": 168 },
   "targets": [
    {
     "query": "from(bucket: \"nesquic\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"nesquic_io\" and r._field == \"volume_kb_sum\")\n  |> filter(fn: (r) => r.library == \"xquic\" and r.mode == \"client\" and r.job == \"delay20\")\n  |> filter(fn: (r) => r.nesquic_run =~ /^${nesquic_run:regex}$/)\n  |> rename(columns: {\"_value\": \"volume_kb_sum\"})\n  |> group()"
    }
   ]
  },
  {
   "title": "ACK Frames Sent",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12.0, "x": 0, "y": 176 },
   "targets": [
    {
     "query": "from(bucket: \"nesquic\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"nesquic_quic\" and r._field == \"acks_sent\")\n  |> filter(fn: (r) => r.library == \"xquic\" and r.job == \"delay20\")\n  |> filter(fn: (r) => r.nesquic_run =~ /^${nesquic_run:regex}$/)\n  |> rename(columns: {\"_value\": \"acks_sent\"})\n  |> group()"
    }
   ]
  },
  {
   "title": "Packets Sent",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12.0, "x": 12.0, "y": 176 },
   "targets": [
    {
     "query": "from(bucket: \"nesquic\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"nesquic_quic\" and r._field == \"packets_sent\")\n  |> filter(fn: (r) => r.library == \"xquic\" and r.job == \"delay20\")\n  |> filter(fn: (r) => r.nesquic_run =~ /^${nesquic_run:regex}$/)\n  |> rename(columns: {\"_value\": \"packets_sent\"})\n  |> group()"
    }
   ]
  },
  { "title": "Driving", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 184 } },
  {
   "type": "text",
   "gridPos": { "h": 1.2, "w": 24, "x": 0, "y": 192 },
   "options": {
    "content": "This experiment simulates a cell phone that is connected to an LTE network while driving. 50ms delay are applied to the traffic."
   }
  },
  {
   "title": "Server I/O Syscalls",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12.0, "x": 0, "y": 200 },
   "targets": [
    {
     "query": "from(bucket: \"nesquic\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"nesquic_io\" and r._field == \"count\")\n  |> filter(fn: (r) => r.library == \"xquic\" and r.mode == \"server\" and r.job == \"driving\")\n  |> filter(fn: (r) => r.nesquic_run =~ /^${nesquic_run:regex}$/)\n  |> rename(columns: {\"_value\": \"count\"})\n  |> group()"
    }
   ]
  },
  {
   "title": "Server I/O Data Volume",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12.0, "x": 12.0, "y": 208 },
   "targets": [
    {
     "query": "from(bucket: \"nesquic\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"nesquic_io\" and r._field == \"volume_kb_sum\")\n  |> filter(fn: (r) => r.library == \"xquic\" and r.mode == \"server\" and r.job == \"driving\")\n  |> filter(fn: (r) => r.nesquic_run =~ /^${nesquic_run:regex}$/)\n  |> rename(columns: {\"_value\": \"volume_kb_sum\"})\n  |> group()"
    }
   ]
  },
  {
   "title": "Client I/O Syscalls",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12.0, "x": 0, "y": 216 },
   "targets": [
    {
     "query": "from(bucket: \"nesquic\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"nesquic_io\" and r._field == \"count\")\n  |> filter(fn: (r) => r.library == \"xquic\" and r.mode == \"client\" and r.job == \"driving\")\n  |> filter(fn: (r) => r.nesquic_run =~ /^${nesquic_run:regex}$/)\n  |> rename(columns: {\"_value\": \"count\"})\n  |> group()"
    }
   ]
  },
  {
   "title": "Client I/O Data Volume",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12.0, "x": 12.0, "y": 224 },
   "targets": [
    {
     "query": "from(bucket: \"nesquic\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"nesquic_io\" and r._field == \"volume_kb_sum\")\n  |> filter(fn: (r) => r.library == \"xquic\" and r.mode == \"client\" and r.job == \"driving\")\n  |> filter(fn: (r) => r.nesquic_run =~ /^${nesquic_run:regex}$/)\n  |> rename(columns: {\"_value\": \"volume_kb_sum\"})\n  |> group()"
    }
   ]
  },
  {
   "title": "ACK Frames Sent",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12.0, "x": 0, "y": 232 },
   "targets": [
    {
     "query": "from(bucket: \"nesquic\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"nesquic_quic\" and r._field == \"acks_sent\")\n  |> filter(fn: (r) => r.library == \"xquic\" and r.job == \"driving\")\n  |> filter(fn: (r) => r.nesquic_run =~ /^${nesquic_run:regex}$/)\n  |> rename(columns: {\"_value\": \"acks_sent\"})\n  |> group()"
    }
   ]
  },
  {
   "title": "Packets Sent",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12.0, "x": 12.0, "y": 232 },
   "targets": [
    {
     "query": "from(bucket: \"nesquic\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"nesquic_quic\" and r._field == \"packets_sent\")\n  |> filter(fn: (r) => r.library == \"xquic\" and r.job == \"driving\")\n  |> filter(fn: (r) => r.nesquic_run =~ /^${nesquic_run:regex}$/)\n  |> rename(columns: {\"_value\": \"packets_sent\"})\n  |> group()"
    }
   ]
  }
 ]
}