// SPDX-License-Identifier: (LGPL-2.1 OR BSD-2-Clause)
//
// THIS FILE IS AUTOGENERATED BY CARGO-LIBBPF-GEN!

pub use self::imp::*;

#[allow(renamed_and_removed_lints)]
#[allow(dead_code)]
#[allow(non_snake_case)]
#[allow(non_camel_case_types)]
#[allow(clippy::absolute_paths)]
#[allow(clippy::upper_case_acronyms)]
#[allow(clippy::zero_repeat_side_effects)]
#[warn(single_use_lifetimes)]
mod imp {
    #[allow(unused_imports, clippy::wildcard_imports)]
    use super::*;
    use libbpf_rs::libbpf_sys;
    use libbpf_rs::skel::OpenSkel;
    use libbpf_rs::skel::Skel;
    use libbpf_rs::skel::SkelBuilder;
    use libbpf_rs::AsRawLibbpf as _;
    use libbpf_rs::MapCore as _;
    fn build_skel_config(
    ) -> libbpf_rs::Result<libbpf_rs::__internal_skel::ObjectSkeletonConfig<'static>> {
        let mut builder = libbpf_rs::__internal_skel::ObjectSkeletonConfigBuilder::new(DATA);
        builder
            .name("metrics_bpf")
            .map("metrics_.bss", true)
            .prog("do_writev");
        builder.build()
    }
    pub struct OpenMetricsMaps<'obj> {
        pub bss: libbpf_rs::OpenMapMut<'obj>,
        pub bss_data: Option<&'obj mut types::bss>,
        _phantom: std::marker::PhantomData<&'obj ()>,
    }

    impl<'obj> OpenMetricsMaps<'obj> {
        #[allow(unused_variables)]
        unsafe fn new(
            config: &libbpf_rs::__internal_skel::ObjectSkeletonConfig<'_>,
            object: &mut libbpf_rs::OpenObject,
        ) -> libbpf_rs::Result<Self> {
            let mut bss = None;
            let object = unsafe {
                std::mem::transmute::<&mut libbpf_rs::OpenObject, &'obj mut libbpf_rs::OpenObject>(
                    object,
                )
            };
            #[allow(clippy::never_loop)]
            for map in object.maps_mut() {
                let name = map.name().to_str().ok_or_else(|| {
                    libbpf_rs::Error::from(std::io::Error::new(
                        std::io::ErrorKind::InvalidData,
                        "map has invalid name",
                    ))
                })?;
                #[allow(clippy::match_single_binding)]
                match name {
                    "metrics_.bss" => bss = Some(map),
                    _ => panic!("encountered unexpected map: `{name}`"),
                }
            }

            let slf = Self {
                bss: bss.expect("map `bss` not present"),
                bss_data: unsafe {
                    config
                        .map_mmap_ptr(0)
                        .expect("BPF map `bss` does not have mmap pointer")
                        .cast::<types::bss>()
                        .as_mut()
                },
                _phantom: std::marker::PhantomData,
            };
            Ok(slf)
        }
    }
    pub struct MetricsMaps<'obj> {
        pub bss: libbpf_rs::MapMut<'obj>,
        pub bss_data: Option<&'obj mut types::bss>,
        _phantom: std::marker::PhantomData<&'obj ()>,
    }

    impl<'obj> MetricsMaps<'obj> {
        #[allow(unused_variables)]
        unsafe fn new(
            config: &libbpf_rs::__internal_skel::ObjectSkeletonConfig<'_>,
            object: &mut libbpf_rs::Object,
        ) -> libbpf_rs::Result<Self> {
            let mut bss = None;
            let object = unsafe {
                std::mem::transmute::<&mut libbpf_rs::Object, &'obj mut libbpf_rs::Object>(object)
            };
            #[allow(clippy::never_loop)]
            for map in object.maps_mut() {
                let name = map.name().to_str().ok_or_else(|| {
                    libbpf_rs::Error::from(std::io::Error::new(
                        std::io::ErrorKind::InvalidData,
                        "map has invalid name",
                    ))
                })?;
                #[allow(clippy::match_single_binding)]
                match name {
                    "metrics_.bss" => bss = Some(map),
                    _ => panic!("encountered unexpected map: `{name}`"),
                }
            }

            let slf = Self {
                bss: bss.expect("map `bss` not present"),
                bss_data: unsafe {
                    config
                        .map_mmap_ptr(0)
                        .expect("BPF map `bss` does not have mmap pointer")
                        .cast::<types::bss>()
                        .as_mut()
                },
                _phantom: std::marker::PhantomData,
            };
            Ok(slf)
        }
    }
    pub struct OpenMetricsProgs<'obj> {
        pub do_writev: libbpf_rs::OpenProgramMut<'obj>,
        _phantom: std::marker::PhantomData<&'obj ()>,
    }

    impl<'obj> OpenMetricsProgs<'obj> {
        unsafe fn new(object: &mut libbpf_rs::OpenObject) -> libbpf_rs::Result<Self> {
            let mut do_writev = None;
            let object = unsafe {
                std::mem::transmute::<&mut libbpf_rs::OpenObject, &'obj mut libbpf_rs::OpenObject>(
                    object,
                )
            };
            for prog in object.progs_mut() {
                let name = prog.name().to_str().ok_or_else(|| {
                    libbpf_rs::Error::from(std::io::Error::new(
                        std::io::ErrorKind::InvalidData,
                        "prog has invalid name",
                    ))
                })?;
                match name {
                    "do_writev" => do_writev = Some(prog),
                    _ => panic!("encountered unexpected prog: `{name}`"),
                }
            }

            let slf = Self {
                do_writev: do_writev.expect("prog `do_writev` not present"),
                _phantom: std::marker::PhantomData,
            };
            Ok(slf)
        }
    }
    pub struct MetricsProgs<'obj> {
        pub do_writev: libbpf_rs::ProgramMut<'obj>,
        _phantom: std::marker::PhantomData<&'obj ()>,
    }

    impl<'obj> MetricsProgs<'obj> {
        #[allow(unused_variables)]
        fn new(open_progs: OpenMetricsProgs<'obj>) -> Self {
            Self {
                do_writev: unsafe {
                    libbpf_rs::ProgramMut::new_mut(open_progs.do_writev.as_libbpf_object().as_mut())
                },
                _phantom: std::marker::PhantomData,
            }
        }
    }
    struct OwnedRef<'obj, O> {
        object: Option<&'obj mut std::mem::MaybeUninit<O>>,
    }

    impl<'obj, O> OwnedRef<'obj, O> {
        /// # Safety
        /// The object has to be initialized.
        unsafe fn new(object: &'obj mut std::mem::MaybeUninit<O>) -> Self {
            Self {
                object: Some(object),
            }
        }

        fn as_ref(&self) -> &O {
            // SAFETY: As per the contract during construction, the
            //         object has to be initialized.
            unsafe { self.object.as_ref().unwrap().assume_init_ref() }
        }

        fn as_mut(&mut self) -> &mut O {
            // SAFETY: As per the contract during construction, the
            //         object has to be initialized.
            unsafe { self.object.as_mut().unwrap().assume_init_mut() }
        }

        fn take(mut self) -> &'obj mut std::mem::MaybeUninit<O> {
            self.object.take().unwrap()
        }
    }

    impl<O> Drop for OwnedRef<'_, O> {
        fn drop(&mut self) {
            if let Some(object) = &mut self.object {
                unsafe { object.assume_init_drop() }
            }
        }
    }

    #[derive(Default)]
    pub struct MetricsSkelBuilder {
        pub obj_builder: libbpf_rs::ObjectBuilder,
    }

    impl<'obj> MetricsSkelBuilder {
        fn open_opts_impl(
            self,
            open_opts: *const libbpf_sys::bpf_object_open_opts,
            object: &'obj mut std::mem::MaybeUninit<libbpf_rs::OpenObject>,
        ) -> libbpf_rs::Result<OpenMetricsSkel<'obj>> {
            let skel_config = build_skel_config()?;
            let skel_ptr = skel_config.as_libbpf_object();

            let ret =
                unsafe { libbpf_sys::bpf_object__open_skeleton(skel_ptr.as_ptr(), open_opts) };
            if ret != 0 {
                return Err(libbpf_rs::Error::from_raw_os_error(-ret));
            }

            // SAFETY: `skel_ptr` points to a valid object after the
            //         open call.
            let obj_ptr = unsafe { *skel_ptr.as_ref().obj };
            // SANITY: `bpf_object__open_skeleton` should have
            //         allocated the object.
            let obj_ptr = std::ptr::NonNull::new(obj_ptr).unwrap();
            // SAFETY: `obj_ptr` points to an opened object after
            //         skeleton open.
            let obj = unsafe { libbpf_rs::OpenObject::from_ptr(obj_ptr) };
            let _obj = object.write(obj);
            // SAFETY: We just wrote initialized data to `object`.
            let mut obj_ref = unsafe { OwnedRef::new(object) };

            #[allow(unused_mut)]
            let mut skel = OpenMetricsSkel {
                maps: unsafe { OpenMetricsMaps::new(&skel_config, obj_ref.as_mut())? },
                progs: unsafe { OpenMetricsProgs::new(obj_ref.as_mut())? },
                obj: obj_ref,
                // SAFETY: Our `struct_ops` type contains only pointers,
                //         which are allowed to be NULL.
                // TODO: Generate and use a `Default` representation
                //       instead, to cut down on unsafe code.
                struct_ops: unsafe { std::mem::zeroed() },
                skel_config,
            };

            Ok(skel)
        }
    }

    impl<'obj> SkelBuilder<'obj> for MetricsSkelBuilder {
        type Output = OpenMetricsSkel<'obj>;
        fn open(
            self,
            object: &'obj mut std::mem::MaybeUninit<libbpf_rs::OpenObject>,
        ) -> libbpf_rs::Result<OpenMetricsSkel<'obj>> {
            self.open_opts_impl(std::ptr::null(), object)
        }

        fn open_opts(
            self,
            open_opts: libbpf_sys::bpf_object_open_opts,
            object: &'obj mut std::mem::MaybeUninit<libbpf_rs::OpenObject>,
        ) -> libbpf_rs::Result<OpenMetricsSkel<'obj>> {
            self.open_opts_impl(&open_opts, object)
        }

        fn object_builder(&self) -> &libbpf_rs::ObjectBuilder {
            &self.obj_builder
        }
        fn object_builder_mut(&mut self) -> &mut libbpf_rs::ObjectBuilder {
            &mut self.obj_builder
        }
    }

    #[derive(Debug, Clone)]
    #[repr(C)]
    pub struct StructOps {}

    impl StructOps {}
    pub mod types {
        #[allow(unused_imports)]
        use super::*;
        #[derive(Debug, Default, Copy, Clone)]
        #[repr(C)]
        pub struct pt_regs {
            pub r15: u64,
            pub r14: u64,
            pub r13: u64,
            pub r12: u64,
            pub bp: u64,
            pub bx: u64,
            pub r11: u64,
            pub r10: u64,
            pub r9: u64,
            pub r8: u64,
            pub ax: u64,
            pub cx: u64,
            pub dx: u64,
            pub si: u64,
            pub di: u64,
            pub orig_ax: u64,
            pub ip: u64,
            pub __anon_pt_regs_1: __anon_pt_regs_1,
            pub flags: u64,
            pub sp: u64,
            pub __anon_pt_regs_2: __anon_pt_regs_2,
        }
        #[derive(Copy, Clone)]
        #[repr(C)]
        pub union __anon_pt_regs_1 {
            pub cs: u16,
            pub csx: u64,
            pub fred_cs: fred_cs,
        }
        impl std::fmt::Debug for __anon_pt_regs_1 {
            fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
                write!(f, "(???)")
            }
        }
        impl Default for __anon_pt_regs_1 {
            fn default() -> Self {
                Self { cs: u16::default() }
            }
        }
        #[derive(Copy, Clone)]
        #[repr(C)]
        pub union __anon_pt_regs_2 {
            pub ss: u16,
            pub ssx: u64,
            pub fred_ss: fred_ss,
        }
        impl std::fmt::Debug for __anon_pt_regs_2 {
            fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
                write!(f, "(???)")
            }
        }
        impl Default for __anon_pt_regs_2 {
            fn default() -> Self {
                Self { ss: u16::default() }
            }
        }
        #[derive(Debug, Default, Copy, Clone)]
        #[repr(C)]
        pub struct fred_cs {
            pub __pad_0: [u8; 8],
        }
        #[derive(Debug, Default, Copy, Clone)]
        #[repr(C)]
        pub struct fred_ss {
            pub __pad_0: [u8; 8],
        }
        #[derive(Debug, Default, Copy, Clone)]
        #[repr(C)]
        pub struct bpf_iter_num {
            pub __opaque: [u64; 1],
        }
        #[derive(Debug, Copy, Clone)]
        #[repr(C)]
        pub struct license {
            pub LICENSE: [i8; 4],
        }
        #[derive(Debug, Copy, Clone)]
        #[repr(C)]
        pub struct bss {
            pub do_writev_num_calls: i32,
        }
    }
    pub struct OpenMetricsSkel<'obj> {
        obj: OwnedRef<'obj, libbpf_rs::OpenObject>,
        pub maps: OpenMetricsMaps<'obj>,
        pub progs: OpenMetricsProgs<'obj>,
        pub struct_ops: StructOps,
        skel_config: libbpf_rs::__internal_skel::ObjectSkeletonConfig<'obj>,
    }

    impl<'obj> OpenSkel<'obj> for OpenMetricsSkel<'obj> {
        type Output = MetricsSkel<'obj>;
        fn load(self) -> libbpf_rs::Result<MetricsSkel<'obj>> {
            let skel_ptr = self.skel_config.as_libbpf_object().as_ptr();

            let ret = unsafe { libbpf_sys::bpf_object__load_skeleton(skel_ptr) };
            if ret != 0 {
                return Err(libbpf_rs::Error::from_raw_os_error(-ret));
            }

            let obj_ref = self.obj.take();
            let open_obj = std::mem::replace(obj_ref, std::mem::MaybeUninit::uninit());
            // SAFETY: `open_obj` is guaranteed to be properly
            //         initialized as it came from an `OwnedRef`.
            let obj_ptr = unsafe { open_obj.assume_init().take_ptr() };
            // SAFETY: `obj_ptr` points to a loaded object after
            //         skeleton load.
            let obj = unsafe { libbpf_rs::Object::from_ptr(obj_ptr) };
            // SAFETY: `OpenObject` and `Object` are guaranteed to
            //         have the same memory layout.
            let obj_ref = unsafe {
                std::mem::transmute::<
                    &'obj mut std::mem::MaybeUninit<libbpf_rs::OpenObject>,
                    &'obj mut std::mem::MaybeUninit<libbpf_rs::Object>,
                >(obj_ref)
            };
            let _obj = obj_ref.write(obj);
            // SAFETY: We just wrote initialized data to `obj_ref`.
            let mut obj_ref = unsafe { OwnedRef::new(obj_ref) };

            Ok(MetricsSkel {
                maps: unsafe { MetricsMaps::new(&self.skel_config, obj_ref.as_mut())? },
                progs: MetricsProgs::new(self.progs),
                obj: obj_ref,
                struct_ops: self.struct_ops,
                skel_config: self.skel_config,
                links: MetricsLinks::default(),
            })
        }

        fn open_object(&self) -> &libbpf_rs::OpenObject {
            self.obj.as_ref()
        }

        fn open_object_mut(&mut self) -> &mut libbpf_rs::OpenObject {
            self.obj.as_mut()
        }
    }
    #[derive(Default)]
    pub struct MetricsLinks {
        pub do_writev: Option<libbpf_rs::Link>,
    }
    pub struct MetricsSkel<'obj> {
        obj: OwnedRef<'obj, libbpf_rs::Object>,
        pub maps: MetricsMaps<'obj>,
        pub progs: MetricsProgs<'obj>,
        struct_ops: StructOps,
        skel_config: libbpf_rs::__internal_skel::ObjectSkeletonConfig<'obj>,
        pub links: MetricsLinks,
    }

    unsafe impl Send for MetricsSkel<'_> {}
    unsafe impl Sync for MetricsSkel<'_> {}

    impl<'obj> Skel<'obj> for MetricsSkel<'obj> {
        fn object(&self) -> &libbpf_rs::Object {
            self.obj.as_ref()
        }

        fn object_mut(&mut self) -> &mut libbpf_rs::Object {
            self.obj.as_mut()
        }
        fn attach(&mut self) -> libbpf_rs::Result<()> {
            let skel_ptr = self.skel_config.as_libbpf_object().as_ptr();
            let ret = unsafe { libbpf_sys::bpf_object__attach_skeleton(skel_ptr) };
            if ret != 0 {
                return Err(libbpf_rs::Error::from_raw_os_error(-ret));
            }

            self.links = MetricsLinks {
                do_writev: core::ptr::NonNull::new(self.skel_config.prog_link_ptr(0)?)
                    .map(|ptr| unsafe { libbpf_rs::Link::from_ptr(ptr) }),
            };

            Ok(())
        }
    }
    impl MetricsSkel<'_> {
        pub fn struct_ops_raw(&self) -> *const StructOps {
            &self.struct_ops
        }

        pub fn struct_ops(&self) -> &StructOps {
            &self.struct_ops
        }
    }
    const DATA: &[u8] = &[
        127, 69, 76, 70, 2, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 247, 0, 1, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 152, 11, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 64, 0, 0, 0, 0,
        0, 64, 0, 9, 0, 1, 0, 0, 46, 115, 116, 114, 116, 97, 98, 0, 46, 115, 121, 109, 116, 97, 98,
        0, 107, 112, 114, 111, 98, 101, 47, 100, 111, 95, 119, 114, 105, 116, 101, 118, 0, 108,
        105, 99, 101, 110, 115, 101, 0, 46, 98, 115, 115, 0, 109, 101, 116, 114, 105, 99, 115, 46,
        98, 112, 102, 46, 99, 0, 76, 66, 66, 48, 95, 49, 0, 76, 66, 66, 48, 95, 52, 0, 100, 111,
        95, 119, 114, 105, 116, 101, 118, 0, 100, 111, 95, 119, 114, 105, 116, 101, 118, 95, 110,
        117, 109, 95, 99, 97, 108, 108, 115, 0, 98, 112, 102, 95, 105, 116, 101, 114, 95, 110, 117,
        109, 95, 110, 101, 119, 0, 98, 112, 102, 95, 105, 116, 101, 114, 95, 110, 117, 109, 95,
        110, 101, 120, 116, 0, 98, 112, 102, 95, 105, 116, 101, 114, 95, 110, 117, 109, 95, 100,
        101, 115, 116, 114, 111, 121, 0, 76, 73, 67, 69, 78, 83, 69, 0, 46, 114, 101, 108, 107,
        112, 114, 111, 98, 101, 47, 100, 111, 95, 119, 114, 105, 116, 101, 118, 0, 46, 66, 84, 70,
        0, 46, 66, 84, 70, 46, 101, 120, 116, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 47, 0, 0, 0, 4, 0, 241, 255, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 3, 0, 3, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        61, 0, 0, 0, 0, 0, 3, 0, 96, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 68, 0, 0, 0, 0,
        0, 3, 0, 208, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 75, 0, 0, 0, 18, 0, 3, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 248, 0, 0, 0, 0, 0, 0, 0, 85, 0, 0, 0, 17, 0, 5, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 4, 0, 0, 0, 0, 0, 0, 0, 105, 0, 0, 0, 32, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 122, 0, 0, 0, 32, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 140,
        0, 0, 0, 32, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 161, 0, 0, 0, 17, 0,
        4, 0, 0, 0, 0, 0, 0, 0, 0, 0, 4, 0, 0, 0, 0, 0, 0, 0, 121, 23, 104, 0, 0, 0, 0, 0, 121, 22,
        96, 0, 0, 0, 0, 0, 24, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 97, 18, 0, 0, 0, 0, 0,
        0, 7, 2, 0, 0, 1, 0, 0, 0, 99, 33, 0, 0, 0, 0, 0, 0, 191, 161, 0, 0, 0, 0, 0, 0, 7, 1, 0,
        0, 248, 255, 255, 255, 183, 2, 0, 0, 0, 0, 0, 0, 191, 99, 0, 0, 0, 0, 0, 0, 133, 16, 0, 0,
        255, 255, 255, 255, 191, 161, 0, 0, 0, 0, 0, 0, 7, 1, 0, 0, 248, 255, 255, 255, 133, 16, 0,
        0, 255, 255, 255, 255, 21, 0, 10, 0, 0, 0, 0, 0, 97, 1, 0, 0, 0, 0, 0, 0, 61, 97, 8, 0, 0,
        0, 0, 0, 103, 1, 0, 0, 4, 0, 0, 0, 191, 115, 0, 0, 0, 0, 0, 0, 15, 19, 0, 0, 0, 0, 0, 0,
        191, 161, 0, 0, 0, 0, 0, 0, 7, 1, 0, 0, 232, 255, 255, 255, 183, 2, 0, 0, 16, 0, 0, 0, 133,
        0, 0, 0, 112, 0, 0, 0, 101, 0, 242, 255, 255, 255, 255, 255, 191, 161, 0, 0, 0, 0, 0, 0, 7,
        1, 0, 0, 248, 255, 255, 255, 133, 16, 0, 0, 255, 255, 255, 255, 183, 0, 0, 0, 0, 0, 0, 0,
        149, 0, 0, 0, 0, 0, 0, 0, 71, 80, 76, 0, 0, 0, 0, 0, 16, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0,
        6, 0, 0, 0, 88, 0, 0, 0, 0, 0, 0, 0, 10, 0, 0, 0, 7, 0, 0, 0, 112, 0, 0, 0, 0, 0, 0, 0, 10,
        0, 0, 0, 8, 0, 0, 0, 224, 0, 0, 0, 0, 0, 0, 0, 10, 0, 0, 0, 9, 0, 0, 0, 159, 235, 1, 0, 24,
        0, 0, 0, 0, 0, 0, 0, 40, 4, 0, 0, 40, 4, 0, 0, 224, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 2, 0,
        0, 0, 1, 0, 0, 0, 21, 0, 0, 4, 168, 0, 0, 0, 9, 0, 0, 0, 3, 0, 0, 0, 0, 0, 0, 0, 13, 0, 0,
        0, 3, 0, 0, 0, 64, 0, 0, 0, 17, 0, 0, 0, 3, 0, 0, 0, 128, 0, 0, 0, 21, 0, 0, 0, 3, 0, 0, 0,
        192, 0, 0, 0, 25, 0, 0, 0, 3, 0, 0, 0, 0, 1, 0, 0, 28, 0, 0, 0, 3, 0, 0, 0, 64, 1, 0, 0,
        31, 0, 0, 0, 3, 0, 0, 0, 128, 1, 0, 0, 35, 0, 0, 0, 3, 0, 0, 0, 192, 1, 0, 0, 39, 0, 0, 0,
        3, 0, 0, 0, 0, 2, 0, 0, 42, 0, 0, 0, 3, 0, 0, 0, 64, 2, 0, 0, 45, 0, 0, 0, 3, 0, 0, 0, 128,
        2, 0, 0, 48, 0, 0, 0, 3, 0, 0, 0, 192, 2, 0, 0, 51, 0, 0, 0, 3, 0, 0, 0, 0, 3, 0, 0, 54, 0,
        0, 0, 3, 0, 0, 0, 64, 3, 0, 0, 57, 0, 0, 0, 3, 0, 0, 0, 128, 3, 0, 0, 60, 0, 0, 0, 3, 0, 0,
        0, 192, 3, 0, 0, 68, 0, 0, 0, 3, 0, 0, 0, 0, 4, 0, 0, 0, 0, 0, 0, 4, 0, 0, 0, 64, 4, 0, 0,
        71, 0, 0, 0, 3, 0, 0, 0, 128, 4, 0, 0, 77, 0, 0, 0, 3, 0, 0, 0, 192, 4, 0, 0, 0, 0, 0, 0,
        12, 0, 0, 0, 0, 5, 0, 0, 80, 0, 0, 0, 0, 0, 0, 1, 8, 0, 0, 0, 64, 0, 0, 0, 0, 0, 0, 0, 3,
        0, 0, 5, 8, 0, 0, 0, 94, 0, 0, 0, 5, 0, 0, 0, 0, 0, 0, 0, 97, 0, 0, 0, 8, 0, 0, 0, 0, 0, 0,
        0, 101, 0, 0, 0, 11, 0, 0, 0, 0, 0, 0, 0, 109, 0, 0, 0, 0, 0, 0, 8, 6, 0, 0, 0, 113, 0, 0,
        0, 0, 0, 0, 8, 7, 0, 0, 0, 119, 0, 0, 0, 0, 0, 0, 1, 2, 0, 0, 0, 16, 0, 0, 0, 134, 0, 0, 0,
        0, 0, 0, 8, 9, 0, 0, 0, 138, 0, 0, 0, 0, 0, 0, 8, 10, 0, 0, 0, 144, 0, 0, 0, 0, 0, 0, 1, 8,
        0, 0, 0, 64, 0, 0, 0, 101, 0, 0, 0, 3, 0, 0, 132, 8, 0, 0, 0, 94, 0, 0, 0, 8, 0, 0, 0, 0,
        0, 0, 16, 163, 0, 0, 0, 8, 0, 0, 0, 16, 0, 0, 2, 166, 0, 0, 0, 8, 0, 0, 0, 18, 0, 0, 1, 0,
        0, 0, 0, 3, 0, 0, 5, 8, 0, 0, 0, 170, 0, 0, 0, 5, 0, 0, 0, 0, 0, 0, 0, 173, 0, 0, 0, 8, 0,
        0, 0, 0, 0, 0, 0, 177, 0, 0, 0, 13, 0, 0, 0, 0, 0, 0, 0, 177, 0, 0, 0, 10, 0, 0, 132, 8, 0,
        0, 0, 170, 0, 0, 0, 8, 0, 0, 0, 0, 0, 0, 16, 185, 0, 0, 0, 8, 0, 0, 0, 16, 0, 0, 1, 189, 0,
        0, 0, 8, 0, 0, 0, 17, 0, 0, 1, 197, 0, 0, 0, 8, 0, 0, 0, 18, 0, 0, 1, 201, 0, 0, 0, 8, 0,
        0, 0, 32, 0, 0, 8, 208, 0, 0, 0, 8, 0, 0, 0, 48, 0, 0, 4, 213, 0, 0, 0, 8, 0, 0, 0, 56, 0,
        0, 1, 221, 0, 0, 0, 8, 0, 0, 0, 57, 0, 0, 1, 224, 0, 0, 0, 8, 0, 0, 0, 58, 0, 0, 1, 231, 0,
        0, 0, 8, 0, 0, 0, 60, 0, 0, 4, 0, 0, 0, 0, 1, 0, 0, 13, 15, 0, 0, 0, 239, 0, 0, 0, 1, 0, 0,
        0, 243, 0, 0, 0, 0, 0, 0, 1, 4, 0, 0, 0, 32, 0, 0, 1, 247, 0, 0, 0, 1, 0, 0, 12, 14, 0, 0,
        0, 0, 0, 0, 0, 3, 0, 0, 13, 15, 0, 0, 0, 0, 0, 0, 0, 18, 0, 0, 0, 0, 0, 0, 0, 15, 0, 0, 0,
        0, 0, 0, 0, 15, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 19, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 4, 8, 0,
        0, 0, 14, 1, 0, 0, 20, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 3, 0, 0, 0, 0, 9, 0, 0, 0,
        21, 0, 0, 0, 1, 0, 0, 0, 23, 1, 0, 0, 0, 0, 0, 1, 4, 0, 0, 0, 32, 0, 0, 0, 43, 1, 0, 0, 2,
        0, 0, 12, 17, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 13, 24, 0, 0, 0, 0, 0, 0, 0, 18, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 2, 15, 0, 0, 0, 60, 1, 0, 0, 2, 0, 0, 12, 23, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
        13, 0, 0, 0, 0, 0, 0, 0, 0, 18, 0, 0, 0, 78, 1, 0, 0, 2, 0, 0, 12, 26, 0, 0, 0, 99, 1, 0,
        0, 0, 0, 0, 1, 1, 0, 0, 0, 8, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 3, 0, 0, 0, 0, 28, 0, 0, 0, 21,
        0, 0, 0, 4, 0, 0, 0, 104, 1, 0, 0, 0, 0, 0, 14, 29, 0, 0, 0, 1, 0, 0, 0, 112, 1, 0, 0, 0,
        0, 0, 14, 15, 0, 0, 0, 1, 0, 0, 0, 187, 2, 0, 0, 1, 0, 0, 15, 4, 0, 0, 0, 30, 0, 0, 0, 0,
        0, 0, 0, 4, 0, 0, 0, 195, 2, 0, 0, 1, 0, 0, 15, 4, 0, 0, 0, 31, 0, 0, 0, 0, 0, 0, 0, 4, 0,
        0, 0, 200, 2, 0, 0, 3, 0, 0, 15, 0, 0, 0, 0, 22, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 25, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 27, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 112, 116, 95, 114, 101,
        103, 115, 0, 114, 49, 53, 0, 114, 49, 52, 0, 114, 49, 51, 0, 114, 49, 50, 0, 98, 112, 0,
        98, 120, 0, 114, 49, 49, 0, 114, 49, 48, 0, 114, 57, 0, 114, 56, 0, 97, 120, 0, 99, 120, 0,
        100, 120, 0, 115, 105, 0, 100, 105, 0, 111, 114, 105, 103, 95, 97, 120, 0, 105, 112, 0,
        102, 108, 97, 103, 115, 0, 115, 112, 0, 117, 110, 115, 105, 103, 110, 101, 100, 32, 108,
        111, 110, 103, 0, 99, 115, 0, 99, 115, 120, 0, 102, 114, 101, 100, 95, 99, 115, 0, 117, 49,
        54, 0, 95, 95, 117, 49, 54, 0, 117, 110, 115, 105, 103, 110, 101, 100, 32, 115, 104, 111,
        114, 116, 0, 117, 54, 52, 0, 95, 95, 117, 54, 52, 0, 117, 110, 115, 105, 103, 110, 101,
        100, 32, 108, 111, 110, 103, 32, 108, 111, 110, 103, 0, 115, 108, 0, 119, 102, 101, 0, 115,
        115, 0, 115, 115, 120, 0, 102, 114, 101, 100, 95, 115, 115, 0, 115, 116, 105, 0, 115, 119,
        101, 118, 101, 110, 116, 0, 110, 109, 105, 0, 118, 101, 99, 116, 111, 114, 0, 116, 121,
        112, 101, 0, 101, 110, 99, 108, 97, 118, 101, 0, 108, 109, 0, 110, 101, 115, 116, 101, 100,
        0, 105, 110, 115, 110, 108, 101, 110, 0, 99, 116, 120, 0, 105, 110, 116, 0, 100, 111, 95,
        119, 114, 105, 116, 101, 118, 0, 98, 112, 102, 95, 105, 116, 101, 114, 95, 110, 117, 109,
        0, 95, 95, 111, 112, 97, 113, 117, 101, 0, 95, 95, 65, 82, 82, 65, 89, 95, 83, 73, 90, 69,
        95, 84, 89, 80, 69, 95, 95, 0, 98, 112, 102, 95, 105, 116, 101, 114, 95, 110, 117, 109, 95,
        110, 101, 119, 0, 98, 112, 102, 95, 105, 116, 101, 114, 95, 110, 117, 109, 95, 110, 101,
        120, 116, 0, 98, 112, 102, 95, 105, 116, 101, 114, 95, 110, 117, 109, 95, 100, 101, 115,
        116, 114, 111, 121, 0, 99, 104, 97, 114, 0, 76, 73, 67, 69, 78, 83, 69, 0, 100, 111, 95,
        119, 114, 105, 116, 101, 118, 95, 110, 117, 109, 95, 99, 97, 108, 108, 115, 0, 47, 108,
        111, 99, 97, 108, 47, 104, 111, 109, 101, 47, 108, 97, 117, 114, 105, 110, 98, 47, 112,
        114, 111, 106, 115, 47, 110, 101, 115, 113, 117, 105, 99, 47, 110, 101, 115, 113, 117, 105,
        99, 47, 115, 114, 99, 47, 109, 101, 116, 114, 105, 99, 115, 47, 109, 101, 116, 114, 105,
        99, 115, 46, 98, 112, 102, 46, 99, 0, 105, 110, 116, 32, 66, 80, 70, 95, 75, 80, 82, 79,
        66, 69, 40, 100, 111, 95, 119, 114, 105, 116, 101, 118, 44, 32, 117, 110, 115, 105, 103,
        110, 101, 100, 32, 108, 111, 110, 103, 32, 102, 100, 44, 32, 99, 111, 110, 115, 116, 32,
        115, 116, 114, 117, 99, 116, 32, 105, 111, 118, 101, 99, 32, 42, 118, 101, 99, 44, 32, 117,
        110, 115, 105, 103, 110, 101, 100, 32, 108, 111, 110, 103, 32, 118, 108, 101, 110, 44, 32,
        114, 119, 102, 95, 116, 32, 102, 108, 97, 103, 115, 41, 32, 123, 0, 32, 32, 32, 32, 100,
        111, 95, 119, 114, 105, 116, 101, 118, 95, 110, 117, 109, 95, 99, 97, 108, 108, 115, 43,
        43, 59, 0, 32, 32, 32, 32, 98, 112, 102, 95, 102, 111, 114, 40, 105, 44, 32, 48, 44, 32,
        118, 108, 101, 110, 41, 32, 123, 0, 32, 32, 32, 32, 32, 32, 32, 32, 105, 102, 32, 40, 98,
        112, 102, 95, 112, 114, 111, 98, 101, 95, 114, 101, 97, 100, 95, 117, 115, 101, 114, 40,
        38, 105, 111, 118, 44, 32, 115, 105, 122, 101, 111, 102, 40, 115, 116, 114, 117, 99, 116,
        32, 105, 111, 118, 101, 99, 41, 44, 32, 118, 101, 99, 32, 43, 32, 105, 41, 32, 60, 32, 48,
        41, 32, 123, 0, 48, 58, 49, 51, 0, 48, 58, 49, 50, 0, 108, 105, 99, 101, 110, 115, 101, 0,
        46, 98, 115, 115, 0, 46, 107, 115, 121, 109, 115, 0, 107, 112, 114, 111, 98, 101, 47, 100,
        111, 95, 119, 114, 105, 116, 101, 118, 0, 159, 235, 1, 0, 32, 0, 0, 0, 0, 0, 0, 0, 20, 0,
        0, 0, 20, 0, 0, 0, 188, 0, 0, 0, 208, 0, 0, 0, 44, 0, 0, 0, 8, 0, 0, 0, 207, 2, 0, 0, 1, 0,
        0, 0, 0, 0, 0, 0, 16, 0, 0, 0, 16, 0, 0, 0, 207, 2, 0, 0, 11, 0, 0, 0, 0, 0, 0, 0, 132, 1,
        0, 0, 200, 1, 0, 0, 5, 88, 0, 0, 16, 0, 0, 0, 132, 1, 0, 0, 48, 2, 0, 0, 24, 100, 0, 0, 64,
        0, 0, 0, 132, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 72, 0, 0, 0, 132, 1, 0, 0, 75, 2, 0, 0, 5,
        112, 0, 0, 104, 0, 0, 0, 132, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 112, 0, 0, 0, 132, 1, 0, 0,
        75, 2, 0, 0, 5, 112, 0, 0, 136, 0, 0, 0, 132, 1, 0, 0, 75, 2, 0, 0, 5, 112, 0, 0, 144, 0,
        0, 0, 132, 1, 0, 0, 101, 2, 0, 0, 65, 120, 0, 0, 184, 0, 0, 0, 132, 1, 0, 0, 101, 2, 0, 0,
        13, 120, 0, 0, 216, 0, 0, 0, 132, 1, 0, 0, 75, 2, 0, 0, 5, 112, 0, 0, 232, 0, 0, 0, 132, 1,
        0, 0, 200, 1, 0, 0, 5, 88, 0, 0, 16, 0, 0, 0, 207, 2, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 2, 0,
        0, 0, 177, 2, 0, 0, 0, 0, 0, 0, 8, 0, 0, 0, 2, 0, 0, 0, 182, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 1, 0, 0, 0, 3, 0, 0, 0, 32, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 64,
        0, 0, 0, 0, 0, 0, 0, 204, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 9, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 16, 1, 0, 0, 0, 0, 0, 0, 8, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 8, 0, 0,
        0, 0, 0, 0, 0, 24, 0, 0, 0, 0, 0, 0, 0, 17, 0, 0, 0, 1, 0, 0, 0, 6, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 24, 2, 0, 0, 0, 0, 0, 0, 248, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 8, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 34, 0, 0, 0, 1, 0, 0, 0, 3, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 16, 3, 0, 0, 0, 0, 0, 0, 4, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 42, 0, 0, 0, 8, 0, 0, 0,
        3, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 20, 3, 0, 0, 0, 0, 0, 0, 4, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 4, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 169, 0, 0, 0,
        9, 0, 0, 0, 64, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 24, 3, 0, 0, 0, 0, 0, 0, 64,
        0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 3, 0, 0, 0, 8, 0, 0, 0, 0, 0, 0, 0, 16, 0, 0, 0, 0, 0, 0,
        0, 190, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 88, 3, 0, 0,
        0, 0, 0, 0, 32, 7, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 8, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 195, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        120, 10, 0, 0, 0, 0, 0, 0, 28, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 8, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    ];
}
