name: nesquic

networks:
    nesquic:
        driver: bridge
        driver_opts:
            com.docker.network.bridge.name: nesquic

volumes:
    grafana_data:
    influxdb_data:

services:
    influxdb:
        image: influxdb:2
        container_name: influxdb
        networks:
            - nesquic
        restart: unless-stopped
        ports:
            - "8086:8086"
        volumes:
            - influxdb_data:/var/lib/influxdb2
        environment:
            - DOCKER_INFLUXDB_INIT_MODE=setup
            - DOCKER_INFLUXDB_INIT_USERNAME=${INFLUX_ADMIN_USER:-admin}
            - DOCKER_INFLUXDB_INIT_PASSWORD=${INFLUX_ADMIN_PASSWORD:-nesquicadmin}
            - DOCKER_INFLUXDB_INIT_ORG=${INFLUX_ORG:-nesquic}
            - DOCKER_INFLUXDB_INIT_BUCKET=${INFLUX_BUCKET:-nesquic}
            - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=${INFLUX_TOKEN:-nesquic-token}

    grafana:
        image: grafana/grafana:latest
        container_name: grafana
        networks:
            - nesquic
        restart: unless-stopped
        ports:
            - "3000:3000"
        depends_on:
            - influxdb
        user: root
        volumes:
            - grafana_data:/var/lib/grafana
            - ./grafana/datasource.yml:/etc/grafana/provisioning/datasources/nesquic.yml:ro
            - ./grafana/dashboard.yml:/etc/grafana/provisioning/dashboards/nesquic.yml:ro
            - ./grafana/dashboard:/var/lib/grafana/dashboards:ro
        environment:
            - GF_SECURITY_ADMIN_USER=${GF_ADMIN_USER:-admin}
            - GF_SECURITY_ADMIN_PASSWORD=${GF_ADMIN_PASSWORD:-admin}
            - GF_AUTH_ANONYMOUS_ENABLED=true
            - GF_AUTH_ANONYMOUS_ORG_NAME=Main Org.
            - GF_AUTH_ANONYMOUS_ORG_ROLE=Viewer
            - GF_AUTH_DISABLE_LOGIN_FORM=true
            - GF_USERS_ALLOW_SIGN_UP=false
