FROM rust:1.94.1 AS builder

RUN apt-get update && apt-get install -y \
    libelf-dev \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /workspace
COPY . .

RUN cargo build --release --locked -p quinn-iut --bin nesquic-quinn
