FROM nesquic/rust AS builder

WORKDIR /workspace
COPY Cargo.toml Cargo.lock ./
COPY iut/ iut/
COPY nesquic/ nesquic/
COPY utils/ utils/
COPY res/ res/

RUN cargo build --release --locked -p quinn-iut --bin nesquic-quinn

FROM nesquic/mahimahi

COPY --from=builder /workspace/target/release/nesquic-quinn /usr/local/bin/nesquic-quinn

ENV NESQUIC_BIN=/usr/local/bin/nesquic-quinn
