FROM rust:1.94.1 AS builder

RUN apt-get update && apt-get install -y \
    libelf-dev \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /workspace
COPY . .

RUN cargo build --release --locked -p quinn-iut --bin nesquic-quinn

FROM ubuntu:22.04

COPY --from=builder /workspace/target/release/nesquic-quinn /usr/local/bin/nesquic-quinn
COPY --from=builder /workspace/res /workspace/res

ENTRYPOINT ["/usr/local/bin/nesquic-quinn"]
