name: nesquic

networks:
    nesquic:
        driver: bridge
        driver_opts:
            com.docker.network.bridge.name: nesquic

volumes:
    influxdb_data:

services:
    influxdb:
        image: influxdb:2
        container_name: influxdb
        networks:
            - nesquic
        restart: unless-stopped
        ports:
            - "8086:8086"
        volumes:
            - influxdb_data:/var/lib/influxdb2
        environment:
            - DOCKER_INFLUXDB_INIT_MODE=setup
            - DOCKER_INFLUXDB_INIT_USERNAME=${INFLUX_ADMIN_USER:-admin}
            - DOCKER_INFLUXDB_INIT_PASSWORD=${INFLUX_ADMIN_PASSWORD:-nesquicadmin}
            - DOCKER_INFLUXDB_INIT_ORG=${INFLUX_ORG:-nesquic}
            - DOCKER_INFLUXDB_INIT_BUCKET=${INFLUX_BUCKET:-nesquic}
            - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=${INFLUX_TOKEN:-nesquic-token}

    frontend:
        build:
            context: ..
            dockerfile: docker/Dockerfile.frontend
        image: nesquic/frontend
        container_name: frontend
        networks:
            - nesquic
        restart: unless-stopped
        ports:
            - "3000:80"
        depends_on:
            - influxdb
        volumes:
            - ../res/experiments.yaml:/srv/experiments.yaml:ro
            - ../res/qlog:/srv/qlog:ro
        environment:
            - INFLUX_URL=http://influxdb:8086
            - INFLUX_ORG=${INFLUX_ORG:-nesquic}
            - INFLUX_TOKEN=${INFLUX_TOKEN:-nesquic-token}
