name: CI

on:
    push:
        branches:
            - "**"
            - "!dependabot/**"
    pull_request:
        branches: [main]
    workflow_call:

jobs:
    libraries:
        name: Test ${{ matrix.library }}
        runs-on: ubuntu-24.04
        strategy:
            fail-fast: false
            matrix:
                library: [quinn, quiche, neqo, noq, msquic]
        steps:
            - uses: actions/checkout@v4
            - name: Test
              run: script/test.sh ${{ matrix.library }}
